spring.application.name=billing
# Desactiva la especificación JSON (/v3/api-docs)
springdoc.api-docs.enabled=true

# Desactiva la interfaz gráfica (/swagger-ui/index.html)
springdoc.swagger-ui.enabled=true

# Puerto
server.port=8081